### ISSUE TITLE
 Input byte array has incorrect ending byte

### ISSUE THREAD

**Issue by saiKapilBunni-zessta** [edalexsolutions/equella-ebi#13]
Hi , 
I have tried bulk import and it worked fine with the **sample installer** which you provided in releases.
I have generated an installer from codebase and the  bulk import is not working.

**Logs** : 

15:14:01: Opening a connection to EQUELLA at http://oeq.localhost/test...
15:14:01: Successfully connected to EQUELLA (2023.1.0-Alpha.OSE)
15:14:01: Target collection: 'Introduction To Java'...
15:14:01: Parsing CSV file (/home/zadmin/Desktop/bulkupload/content.csv)...
15:14:01: 4 row(s) found, all rows to be processed
---
15:14:01:  Row 1 [1 of 4]: Processing item...
  Attachment: java.png (87,056 bytes)
    Uploading...15:14:01: ERROR uploading file: Input byte array has incorrect ending byte at 116076
---
15:14:01:  Row 2 [2 of 4]: Processing item...
  Attachment: JDBC1.zip (2.84 MB)
    Uploading...15:14:01: ERROR uploading file: Input byte array has incorrect ending byte at 2796204
---
15:14:01:  Row 3 [3 of 4]: Processing item...
  Attachment: JDBC2.zip (2.84 MB)
    Uploading...15:14:01: ERROR uploading file: Input byte array has incorrect ending byte at 2796204
---
15:14:01:  Row 4 [4 of 4]: Processing item...
  Attachment: JDBC3.zip (2.84 MB)
    Uploading...15:14:01: ERROR uploading file: Input byte array has incorrect ending byte at 2796204
---
15:14:01: Processing complete (success: 0 errors: 4)
15:14:01: Connection successfully closed

OS : ubuntu 20.04
Browsed about the issue and got to know : 
Instead of using **Base64.getDecoder().decode(payload)** , use **Base64.getMimeDecoder().decode(payload)** , accordingly made changes but no use the issue keeps on repeating.

**Comment by AlexPicone** [comment]
Hi, 
The EBI tool is predominantly used by consultants working with the openQUELLA platform.  If you're interested in engaging a consultant to assist with this issue, please contact **info@edalex.com.**  Alternatively, other adopters of the platform may respond to this ticket.
Regards,
Alex

**Comment by saiKapilBunni-zessta** [comment]
Hi, 

The EBI tool uses base64 encoder and base64 decoder while encoding there is some extra character ('=') getting appended to the encrypted key, this is triggering the issue.

For time being, I logged the encrypted key and tried decoding it by removing the extra appended character and it worked fine.

Hope this helps, and please let me know if there is any other fesible solution,

Thankyou.
